[package]

name = "ringbuf"
version = "0.1.0"
authors = [ "dan@danburkert.com" ]

[[lib]]
name = "ringbuf"

[[bin]]
name = "bench"

[dependencies.criterion]
git = "https://github.com/danburkert/criterion.rs.git"

[dependencies.quickcheck]
git = "https://github.com/BurntSushi/quickcheck.git"
